"""Create calculation table

Revision ID: 74807e99eb4b
Revises: 
Create Date: 2026-06-12 10:04:53.581616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74807e99eb4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation',
    sa.Column('calcID', sa.Integer(), nullable=False),
    sa.Column('num1', sa.Integer(), nullable=False),
    sa.Column('num2', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('calcID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation')
    # ### end Alembic commands ###
